package com.signaldrivelogger.data.database.mappers

import com.signaldrivelogger.data.database.entities.SignalRecordEntity
import com.signaldrivelogger.domain.models.SignalRecord
import java.time.Instant
import java.time.ZoneOffset

/**
 * Mapper between SignalRecord (domain model) and SignalRecordEntity (database entity).
 */
object SignalRecordMapper {
    /**
     * Converts SignalRecord (domain) to SignalRecordEntity (database).
     */
    fun toEntity(record: SignalRecord, sessionId: String): SignalRecordEntity {
        return SignalRecordEntity(
            id = 0, // Auto-generated by Room
            session_id = sessionId,
            timestamp = record.timestamp.toEpochMilli(),
            latitude = record.latitude,
            longitude = record.longitude,
            altitude = record.altitude,
            speed_mps = record.speedMps,
            bearing = record.bearing,
            gps_accuracy = record.gpsAccuracy,
            sim_slot_index = record.simSlotIndex,
            subscription_id = if (record.subscriptionId >= 0) record.subscriptionId else null,
            network_type_raw = record.networkType,
            network_operator = "${record.mcc}${record.mnc}",
            roaming_state = record.isRoaming,
            is_endc_available = record.isEndcAvailable,
            nr_state = record.nrState,
            override_network_type = record.overrideNetworkType,
            dbm = record.signalStrength,
            asu = record.asu,
            lte_earfcn = if (record.earfcn > 0) record.earfcn else null,
            lte_bandwidth = record.lteBandwidth ?: if (record.bandwidth > 0) record.bandwidth else null,
            lte_cqi = if (record.cqi > 0) record.cqi else null,
            lte_rssi = if (record.rssi != 0) record.rssi else null,
            nr_arfcn = if (record.nrarfcn > 0) record.nrarfcn else null,
            nr_csi_rsrp = record.nrCsiRsrp,
            nr_csi_sinr = record.nrCsiSinr,
            nr_ss_rsrp = record.nrSsRsrp,
            nr_ss_sinr = record.nrSsSinr,
            cell_id = record.cellId,
            ci = record.ci,
            enb = record.enb,
            tac = record.tac,
            pci = record.pci,
            rsrq = record.rsrq,
            snr = record.snr,
            timing_advance = record.timingAdvance
        )
    }

    /**
     * Converts SignalRecordEntity (database) to SignalRecord (domain).
     */
    fun toDomain(entity: SignalRecordEntity, simProfile: SimProfileInfo? = null): SignalRecord {
        // Extract MCC and MNC from network_operator
        val mcc = if (entity.network_operator.length >= 3) entity.network_operator.substring(0, 3) else ""
        val mnc = if (entity.network_operator.length > 3) entity.network_operator.substring(3) else ""

        return SignalRecord(
            timestamp = Instant.ofEpochMilli(entity.timestamp),
            latitude = entity.latitude,
            longitude = entity.longitude,
            altitude = entity.altitude,
            signalStrength = entity.dbm,
            cellId = entity.cell_id,
            networkType = entity.network_type_raw,
            asu = entity.asu,
            speedMps = entity.speed_mps,
            bearing = entity.bearing,
            gpsAccuracy = entity.gps_accuracy,
            dataState = "Unknown", // Not stored in entity, would need to be added if needed
            dataActivity = "None", // Not stored in entity
            isRoaming = entity.roaming_state,
            simState = simProfile?.simState ?: "Unknown",
            simOperatorName = simProfile?.simOperatorName ?: "",
            simMcc = simProfile?.simMcc ?: "",
            simMnc = simProfile?.simMnc ?: "",
            operatorName = "", // Not stored in entity
            mcc = mcc,
            mnc = mnc,
            phoneType = "Unknown", // Not stored in entity
            simSlotIndex = entity.sim_slot_index,
            subscriptionId = entity.subscription_id ?: -1,
            simDisplayName = simProfile?.simDisplayName ?: "",
            isEmbedded = simProfile?.isEmbedded ?: false,
            ci = entity.ci,
            enb = entity.enb,
            tac = entity.tac,
            pci = entity.pci,
            bandwidth = entity.lte_bandwidth ?: 0,
            earfcn = entity.lte_earfcn ?: 0,
            nrarfcn = entity.nr_arfcn ?: 0,
            rssi = entity.lte_rssi ?: 0,
            rsrq = entity.rsrq,
            snr = entity.snr,
            cqi = entity.lte_cqi ?: 0,
            timingAdvance = entity.timing_advance,
            isEndcAvailable = entity.is_endc_available,
            nrState = entity.nr_state,
            overrideNetworkType = entity.override_network_type,
            lteBandwidth = entity.lte_bandwidth,
            nrCsiRsrp = entity.nr_csi_rsrp,
            nrCsiSinr = entity.nr_csi_sinr,
            nrSsRsrp = entity.nr_ss_rsrp,
            nrSsSinr = entity.nr_ss_sinr
        )
    }
}

/**
 * Helper data class for SIM profile information when converting entities to domain.
 */
data class SimProfileInfo(
    val simState: String = "Unknown",
    val simOperatorName: String = "",
    val simMcc: String = "",
    val simMnc: String = "",
    val simDisplayName: String = "",
    val isEmbedded: Boolean = false
)
